### ISSUE TITLE
Add max points user can earn for trivia

### ISSUE THREAD

**Issue by flameoflust69** [admiralbullbot/bullbot#15]
Since some people using solver too and its 100% unavoidable for public API trivia, theres should be max question you can answer for example 15-20 each trivia started so users will earn maximum 300-400 points.

**Comment by fraserbaigent** [comment]
How about this, make a list of strings of recent correct answers; if the username appears above a certain number of times in this then message them saying they should take a rest. Delete the first entry in the list after each question and append the latest winner or None if incorrect; similar to the recent questions list. This way the chat won't die and the bot won't talk to itself for hours
