### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by TroyDota** [admiralbullbot/bullbot#31]
Hi i am Troy and i can help you fix the bullbot ive basically repaired all the modules that are in the bot for pajbot v1.4.0 if u want dm me on disc Troy#6185 or i could upload here idk @DatGuy1

**Comment by TroyDota** [comment]
Including bet module as well as duel, playsound, showemote ect. also the annoying bug of the old sub emotes not working due to the twitch api being outdated.

**Comment by DatGuy1** [comment]
I'd rather if issues could be only used for tracking issues. I saw your PR at pajbot and I'll wait for it to be merged.
